### ISSUE TITLE
Installation problem using Composer

### ISSUE THREAD

**Issue by okiwan** [hiqdev/yii2-mfa#2]
After adding repository to composer file and syncing, there are some files missing. For instance, folder "src/behaviors" is missing, and other ones. It seems as if there was a problem when creating the package uploaded to composer.

I would appreciate any kind of feedback on this. Of course, there's always the possibility to manually adding the missing files.

Thank you.

**Comment by hiqsol** [comment]
Sounds strange.
Show me your composer.json please.

**Comment by okiwan** [comment]
Hey, thanks for the help. Here it is:

{
    "name": "nenad/yii2-advanced-template",
    "description": "Improved Yii 2 Advanced Application Template By Nenad Zivkovic",
    "keywords": ["yii2", "framework", "advanced", "improved", "application template", "nenad"],
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "tutorial": "http://www.freetuts.org/tutorial/view?id=6",
        "source": "https://github.com/nenad-zivkovic/yii2-advanced-template"
    },
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "git",
            "url": "https://bitbucket.org/cink/yii2-phpexcel.git"
        },
        {
            "type": "package",
            "package": {
                "name": "hpneo/gmaps.git",
                "version": "0.4.22",
                "source": {
                    "type": "git",
                    "url": "https://github.com/hpneo/gmaps.git",
                    "reference": "tags/0.4.22"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "omgdef/yii2-multilingual-behavior",
                "version": "2.1.2.2",
                "source": {
                    "type": "git",
                    "url": "https://bitbucket.org/cink/yii2-multilingual-behavior.git",
                    "reference": "tags/2.1.2.2"
                },
                "autoload": {
                    "psr-4": {
                        "omgdef\\multilingual\\": "src"
                    }
                },
                "require": {
                    "yiisoft/yii2": "*"
                },
                "require-dev": {
                  "phpunit/phpunit": "4.6.*",
                  "phpunit/dbunit": ">=1.2"
                }
            }
        }
    ],
    "require": {
        "fxp/composer-asset-plugin": "^1.1.2",
        "php": ">=5.4.0",
        "yiisoft/yii2": "^2.0.7",
        "yiisoft/yii2-bootstrap": "^2.0.5",
        "yiisoft/yii2-swiftmailer": "^2.0.4",
        "nenad/yii2-password-strength": "^2.3.0",
        "mihaildev/yii2-ckeditor": "^1.0.1",
        "omgdef/yii2-multilingual-behavior": "2.1.2.2",
        "kartik-v/yii2-widget-activeform": "@dev",
        "kartik-v/yii2-datecontrol": "@dev",
        "kartik-v/yii2-widgets": "^3.4.0",
        "kartik-v/yii2-field-range": "^1.3.0",
        "codemix/yii2-localeurls": "1.3.0",
        "hpneo/gmaps.git": "0.4.22",
        "xj/yii2-bootbox-widget": "^1.0.3",
        "yiisoft/yii2-elasticsearch": "^2.0",
        "moonlandsoft/yii2-phpexcel": "^1.1.2",
        "linslin/yii2-curl": "^1.0.7",
        "yiisoft/yii2-imagine": "^2.0.3",
        "ramsey/uuid": "^3.2",
        "aws/aws-sdk-php": "^3.15",
        "aws/aws-php-sns-message-validator": "^1.1",
        "hiqdev/yii2-mfa": "^0.0.1"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*",
        "codeception/specify": "*",
        "codeception/verify": "*"
    },
    "config": {
        "vendor-dir": "_protected/vendor",
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "_protected/vendor/npm",
            "bower-asset-library": "_protected/vendor/bower"
        }
    }
}

In addition to this... Shouldn't be the ThemeManager included as a requirement in yii2-mfa composer file? It is not right now, and a "Class 'hiqdev\thememanager\widgets\LoginForm' not found" arises.

Appreciate it!

**Comment by hiqsol** [comment]
You require stable version while latest changes were not released.
I've made release 0.1.0
To get it (and later changes) you'll need to change version constraint to "~0.1.0".

**Comment by okiwan** [comment]
My bad. Now that seems to solve the problem. Cheers!

**Comment by hiqsol** [comment]
If you're still using fxp plugin try asset-packagist.org
